<div class="face">
    <ul>
        <li><img src="/images/qq/zz2_thumb.gif" title="[织]" ></li>
        <li><img src="/images/qq/horse2_thumb.gif" title="神马]"></li>
        <li><img src="/images/qq/fuyun_thumb.gif" title="[浮云]"></li>
        <li><img src="/images/qq/geili_thumb.gif" title="[给力]"></li>
        <li><img src="/images/qq/wg_thumb.gif" title="[围观]"></li>
        <li><img src="/images/qq/vw_thumb.gif" title="[威武]"></li>
        <li><img src="/images/qq/panda_thumb.gif" title="[熊猫]"></li>
        <li><img src="/images/qq/rabbit_thumb.gif" title="兔子]"></li>
        <li><img src="/images/qq/otm_thumb.gif" title="[奥特曼]"></li>
        <li><img src="/images/qq/j_thumb.gif" title="[囧]"></li>
        <li><img src="/images/qq/hufen_thumb.gif" title="[互粉]"></li>
        <li><img src="/images/qq/liwu_thumb.gif" title="[礼物]"></li>
        <li><img src="/images/qq/smilea_thumb.gif" title="呵呵]"></li>
        <li><img src="/images/qq/tootha_thumb.gif" title="嘻嘻]"></li>
        <li><img src="/images/qq/laugh.gif" title="[哈哈]"></li>
        <li><img src="/images/qq/tza_thumb.gif" title="[可爱]"></li>
        <li><img src="/images/qq/kl_thumb.gif" title="[可怜]"></li>
        <li><img src="/images/qq/kbsa_thumb.gif" title="[挖鼻屎]"></li>
        <li><img src="/images/qq/cj_thumb.gif" title="[吃惊]"></li>
        <li><img src="/images/qq/shamea_thumb.gif" title="[害羞]"></li>
        <li><img src="/images/qq/zy_thumb.gif" title="[挤眼]"></li>
        <li><img src="/images/qq/bz_thumb.gif" title="[闭嘴]"></li>
        <li><img src="/images/qq/bs2_thumb.gif" title="[鄙视]"></li>
        <li><img src="/images/qq/lovea_thumb.gif" title="[爱你]"></li>
        <li><img src="/images/qq/sada_thumb.gif" title="[泪]"></li>
        <li><img src="/images/qq/heia_thumb.gif" title="[偷笑]"></li>
        <li><img src="/images/qq/qq_thumb.gif" title="[亲亲]"></li>
        <li><img src="/images/qq/sb_thumb.gif" title="[生病]"></li>
        <li><img src="/images/qq/mb_thumb.gif" title="[太开心]"></li>
        <li><img src="/images/qq/ldln_thumb.gif" title="[懒得理你]"></li>
        <li><img src="/images/qq/yhh_thumb.gif" title="[右哼哼]"></li>
        <li><img src="/images/qq/zhh_thumb.gif" title="[左哼哼]"></li>
        <li><img src="/images/qq/x_thumb.gif" title="[嘘]"></li>
        <li><img src="/images/qq/cry.gif" title="[衰]"></li>
        <li><img src="/images/qq/wq_thumb.gif" title="[委屈]"></li>
        <li><img src="/images/qq/t_thumb.gif" title="[吐]"></li>
        <li><img src="/images/qq/k_thumb.gif" title="[打哈气]"></li>
        <li><img src="/images/qq/bba_thumb.gif" title="[抱抱]"></li>
        <li><img src="/images/qq/angrya_thumb.gif" title="[怒]"></li>
        <li><img src="/images/qq/yw_thumb.gif" title="[疑问]"></li>
        <li><img src="/images/qq/cza_thumb.gif" title="[馋嘴]"></li>
        <li><img src="/images/qq/88_thumb.gif" title="[拜拜]"></li>
        <li><img src="/images/qq/sk_thumb.gif" title="[思考]"></li>
        <li><img src="/images/qq/sweata_thumb.gif" title="[汗]"></li>
        <li><img src="/images/qq/sleepya_thumb.gif" title="[困]"></li>
        <li><img src="/images/qq/sleepa_thumb.gif" title="[睡觉]"></li>
        <li><img src="/images/qq/money_thumb.gif" title="[钱]"></li>
        <li><img src="/images/qq/sw_thumb.gif" title="[失望]"></li>
        <li><img src="/images/qq/cool_thumb.gif" title="[酷]"></li>
        <li><img src="/images/qq/hsa_thumb.gif" title="[花心]"></li>
        <li><img src="/images/qq/hatea_thumb.gif" title="[哼]"></li>
        <li><img src="/images/qq/gza_thumb.gif" title="[鼓掌]"></li>
        <li><img src="/images/qq/dizzya_thumb.gif" title="[晕]"></li>
        <li><img src="/images/qq/bs_thumb.gif" title="[悲伤]"></li>
        <li><img src="/images/qq/crazya_thumb.gif" title="[抓狂]"></li>
        <li><img src="/images/qq/h_thumb.gif" title="[黑线]"></li>
        <li><img src="/images/qq/yx_thumb.gif" title="[阴险]"></li>
        <li><img src="/images/qq/nm_thumb.gif" title="[怒骂]"></li>
        <li><img src="/images/qq/hearta_thumb.gif" title="[心]"></li>
        <li><img src="/images/qq/unheart.gif" title="[伤心]"></li>
        <li><img src="/images/qq/pig.gif" title="[猪头]"></li>
        <li><img src="/images/qq/ok_thumb.gif" title="[ok]"></li>
        <li><img src="/images/qq/ye_thumb.gif" title="[耶]"></li>
        <li><img src="/images/qq/good_thumb.gif" title="[good]"></li>
        <li><img src="/images/qq/no_thumb.gif" title="[不要]"></li>
        <li><img src="/images/qq/z2_thumb.gif" title="[赞]"></li>
        <li><img src="/images/qq/come_thumb.gif" title="[来]"></li>
        <li><img src="/images/qq/sad_thumb.gif" title="[弱]"></li>
        <li><img src="/images/qq/lazu_thumb.gif" title="[蜡烛]"></li>
        <li><img src="/images/qq/clock_thumb.gif" title="[钟]"></li>
        <li><img src="/images/qq/cake.gif" title="[蛋糕]"></li>
        <li><img src="/images/qq/m_thumb.gif" title="[话筒]"></li>
        <li><img src="/images/qq/weijin_thumb.gif" title="[围脖]"></li>
        <li><img src="/images/qq/lxhzhuanfa_thumb.gif" title="[转发]"></li>
        <li><img src="/images/qq/lxhluguo_thumb.gif" title="[路过这儿]"></li>
        <li><img src="/images/qq/bofubianlian_thumb.gif" title="[bofu变脸]"></li>
        <li><img src="/images/qq/gbzkun_thumb.gif" title="[gbz困]"></li>
        <li><img src="/images/qq/boboshengmenqi_thumb.gif" title="[生闷气]"></li>
        <li><img src="/images/qq/chn_buyaoya_thumb.gif" title="[不要啊]"></li>
        <li><img src="/images/qq/daxiongleibenxiong_thumb.gif" title="[dx泪奔]"></li>
        <li><img src="/images/qq/cat_yunqizhong_thumb.gif" title="[运气中]"></li>
        <li><img src="/images/qq/youqian_thumb.gif" title="[有钱]"></li>
        <li><img src="/images/qq/cf_thumb.gif" title="[冲锋]"></li>
        <li><img src="/images/qq/camera_thumb.gif" title="[照相机]"></li>
    </ul>
</div>